import Image from "next/image";

const projects = [
  { number:"01", date:"06, JULY 2026", title:"NFC REVIEW AI", description:"拼豆店 AI 评价助手：NFC 一贴进入人群分层，AI 生成 3 版真实感文案并跳转抖音，内置防幻觉与合规校验。", tags:["NFC + LLM","MVP DEMO"], image:"/assets/nfc-prototype-overview-1x1.png", backdrop:"/assets/web-bg-nfc-blue.jpg", tone:"cyan" },
  { number:"02", date:"07, JULY 2026", title:"RAG PROOFREADER", description:"地产口播稿智能校对：术语知识库配合向量/拼音双路检索，只在有依据时建议修改，减少 ASR 专业名词错写。", tags:["RAG","COZE"], image:"/assets/rag-proofreader.png", backdrop:"/assets/web-bg-rag-paper.jpg", tone:"dark" },
  { number:"03", date:"05, JUNE 2026", title:"AI CONTENT OS", description:"地产 IP 内容生产 AI 改造方案：以 RAG 知识库和提示词工程，覆盖 30 万粉丝矩阵从选题到成片的全链路。", tags:["CONTENT","AI WORKFLOW"], image:"/assets/ai-content-os.png", backdrop:"/assets/web-bg-content-pink.jpg", tone:"pink" },
];

export function WebWorks(){return <section id="web-works" className="ww grid-paper">
  <header className="ww-head"><h2 className="pixel" data-reveal>FEATURED<br/>WEB WORKS</h2><p className="sticker mono" data-reveal="pop" style={{"--reveal-delay":"0.3s"} as React.CSSProperties}>让 AI 成为效率杠杆。</p></header>
  <div className="ww-stack">{projects.map((p,index)=><article className={`project ${p.tone}`} style={{zIndex:index+1}} key={p.title}>
    <div className="folder-tabs" aria-hidden="true"><span className={`folder-tab ${p.tone} tab-position-${index}`}>▟ PROJECT {p.number}</span></div>
    <div className="copy"><div className="mono meta">● &nbsp;{p.date}</div><h3>{p.title}</h3><p>{p.description}</p><span className="mono project-state">PROJECT SNAPSHOT</span><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div>
    <div className="image">
      <Image className="image-backdrop" src={p.backdrop} alt="" aria-hidden="true" fill sizes="(max-width: 760px) calc(100vw - 48px), 1px"/>
      <Image className="image-shot" src={p.image} alt={`${p.title} 项目界面预览`} fill sizes="(max-width: 760px) calc(100vw - 72px), 620px"/>
    </div>
  </article>)}</div>
  <style>{`.ww{padding:110px 0 0;overflow:clip}.ww-head{text-align:center;margin-bottom:125px}.ww-head h2{font-size:clamp(52px,6vw,92px);line-height:.85;letter-spacing:-.07em;margin:0}.ww-head p{display:inline-block;background:#f4c54e;padding:13px 18px;margin:30px 0 0;transform:rotate(-3deg);font-size:11px}.ww-stack{width:min(1880px,calc(100% - 70px));margin:auto;padding-bottom:5vh}.project{position:sticky;top:48px;height:calc(100vh - 48px);min-height:650px;display:grid;grid-template-columns:49% 51%;border:2px solid #18130f;margin-bottom:72vh;overflow:visible;box-shadow:0 -1px 0 #18130f}.project:last-child{margin-bottom:0}.project.cyan,.folder-tab.cyan{background:#39c4e5;color:#101010}.project.dark,.folder-tab.dark{background:#171817;color:#fff}.project.pink,.folder-tab.pink{background:#e9005a;color:#fff}.folder-tabs{position:absolute;left:-2px;right:-2px;top:-54px;height:55px;display:flex;align-items:end;overflow:hidden}.folder-tab{height:55px;width:26%;display:flex;align-items:center;justify-content:center;border:2px solid #18130f;border-bottom:0;font:700 13px var(--font-mono);clip-path:polygon(0 0,78% 0,91% 100%,100% 100%,100% 100%,0 100%);margin-right:-2px}.folder-tab.active{width:30%}.copy{padding:70px 32px 30px;display:flex;flex-direction:column;align-items:flex-start}.meta{font-size:12px;margin-bottom:15px;font-weight:700}.copy h3{font-size:clamp(48px,4.8vw,82px);line-height:.92;letter-spacing:-.06em;margin:0 0 16px}.copy p{font-size:15px;line-height:1.38;max-width:360px;margin:0 0 30px}.project-state{font-size:12px;border-bottom:1px solid;padding-bottom:5px}.tags{margin-top:auto;display:flex;gap:9px}.tags span{font:11px var(--font-mono);padding:7px 10px;background:#fff;color:#111;border:1px solid #111;clip-path:polygon(0 0,78% 0,88% 22%,100% 22%,100% 100%,0 100%)}.image{position:relative;margin:18px 18px 18px 0;overflow:hidden;border:2px solid currentColor;background:#fff}.image-backdrop{display:none;pointer-events:none}.image-shot{object-fit:contain;display:block;transition:transform .6s ease}.project:hover .image-shot{transform:scale(1.015)}
  @media(max-width:760px){.ww{padding:75px 0 0}.ww-head{margin-bottom:100px}.ww-head h2{font-size:44px}.ww-stack{width:calc(100% - 20px);padding-bottom:5vh}.project{top:48px;height:calc(100svh - 48px);min-height:650px;grid-template-columns:1fr;margin-bottom:72vh}.folder-tabs{top:-43px;height:44px}.folder-tab{height:44px;width:33%;font-size:8px}.folder-tab.active{width:38%}.copy{padding:32px 18px 18px}.image{margin:0 14px 14px;height:clamp(300px,48svh,430px);background:#f2eee6}.image-backdrop{display:block;object-fit:cover;pointer-events:none}.image-shot{object-fit:contain;box-sizing:border-box;padding:12px;filter:drop-shadow(0 8px 14px rgba(17,13,10,.22))}.project:hover .image-shot{transform:none}.copy h3{font-size:38px}.copy p{font-size:13px;margin-bottom:18px}.tags{margin-top:20px}.tags span{font-size:8px;padding:5px 7px}}`}</style>
  <style>{`.folder-tabs.folder-position-1{padding-left:25%}.folder-tabs.folder-position-2{padding-left:50%}.folder-tabs .folder-tab{flex:0 0 30%}.ww-stack>.project{margin-bottom:0}@media(max-width:760px){.folder-tabs.folder-position-1{padding-left:22%}.folder-tabs.folder-position-2{padding-left:44%}.folder-tabs .folder-tab{flex-basis:42%}.ww-stack>.project{margin-bottom:0}}`}</style>
  <style>{`@media(min-width:761px){.ww-stack{width:min(1240px,calc(100% - 64px));padding-bottom:5vh}.ww-stack>.project{top:110px;height:min(650px,calc(100vh - 180px));min-height:560px}.folder-tabs{top:-48px;height:49px}.folder-tab{height:49px}.copy{padding:54px 28px 25px}.copy h3{font-size:clamp(42px,4vw,64px)}.image{margin:16px 16px 16px 0}}`}</style>
  <style>{`.ww-stack>.project{border-color:transparent;box-shadow:none}.folder-tabs .folder-tab{border-color:transparent}.ww-stack .image{border-color:transparent}`}</style>
  <style>{`.ww-stack .tags{gap:14px}.ww-stack .tags span{min-width:126px;padding:13px 18px;background:#fff;color:#18130f;border:1px solid #18130f;font:16px var(--font-mono);text-align:center;text-transform:none;clip-path:polygon(0 0,78% 0,87% 20%,100% 20%,100% 100%,0 100%)}@media(max-width:760px){.ww-stack .tags{gap:8px}.ww-stack .tags span{min-width:auto;padding:8px 10px;font-size:10px}}`}</style>
  <style>{`.ww-stack .tags span{min-width:0;padding:14px 17px 11px;background:#171817;color:#35c5ec;border:0;font-weight:700;text-transform:uppercase;clip-path:polygon(0 0,26% 0,34% 20%,100% 20%,100% 100%,0 100%)}@media(max-width:760px){.ww-stack .tags span{padding:10px 11px 8px}}`}</style>
  <style>{`.ww-stack .project.cyan .tags span{background:#171817;color:#35c5ec}.ww-stack .project.dark .tags span{background:#fff;color:#171817}.ww-stack .project.pink .tags span{background:#fff;color:#e9005a}`}</style>
  <style>{`.folder-tabs{position:absolute}.folder-tabs .folder-tab{position:absolute;bottom:0;width:30%;margin:0}.folder-tabs .tab-position-0{left:0}.folder-tabs .tab-position-1{left:25%}.folder-tabs .tab-position-2{left:50%}@media(max-width:760px){.folder-tabs .folder-tab{width:42%}.folder-tabs .tab-position-0{left:0}.folder-tabs .tab-position-1{left:22%}.folder-tabs .tab-position-2{left:44%}}`}</style>
</section>}
